
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mys3:
    image: golang:latest  # Utilisation de l'image Go officielle
    container_name: mys3
    volumes:
      - ./app:/app  # Montez le répertoire local `app` dans le conteneur
    working_dir: /app  # Définit le répertoire de travail dans le conteneur
    command: go run main.go  # Commande pour démarrer l'application Go
    ports:
      - "8080:8080"
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    depends_on:
      - minio

volumes:
  minio_data:
